
'use client';

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ClipboardList, FileText, Bot, ArrowRight } from "lucide-react";
import { useRouter } from "next/navigation";
import { useToast } from "@/hooks/use-toast";
import { generateDpp } from "@/ai/flows/generate-dpp";
import { useState } from "react";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { cn } from "@/lib/utils";

export default function MockTestPage() {
  const router = useRouter();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState<'jee' | 'neet' | null>(null);

  const handleGenerateTest = async (examType: 'jee' | 'neet') => {
    setIsLoading(examType);
    toast({
      title: `Generating ${examType.toUpperCase()} Full Syllabus Test...`,
      description: "Please wait while the AI prepares your mock exam.",
    });

    try {
      const testConfig = {
        dppType: 'full-syllabus' as const,
        examType: examType,
      };
      
      const result = await generateDpp(testConfig);
      // Store the entire config which now includes sections
      sessionStorage.setItem('mockTestConfig', JSON.stringify(result));
      router.push('/mock-test/start');

    } catch (error) {
      console.error(`Failed to generate ${examType} test`, error);
      toast({
        title: "Generation Failed",
        description: "Something went wrong while creating your test. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(null);
    }
  };

  return (
    <div className="p-6 md:p-10">
      <div className="space-y-8 max-w-4xl mx-auto">
        <header className="space-y-2 text-center">
            <h1 className="text-4xl md:text-5xl font-headline font-bold tracking-tighter">AI Mock Tests</h1>
            <p className="text-muted-foreground md:text-xl max-w-2xl mx-auto">
                Simulate real exam conditions with full syllabus tests generated by AI, tailored for JEE and NEET patterns.
            </p>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <Card 
              className="bg-secondary/30 border-blue-500/30 p-6 rounded-2xl transition-all group relative overflow-hidden flex flex-col"
            >
                <CardHeader>
                    <CardTitle className="font-headline text-3xl">JEE Main Full Test</CardTitle>
                </CardHeader>
                <CardContent className="flex-1 flex flex-col justify-between">
                    <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                        <li>Physics: 25 Questions</li>
                        <li>Chemistry: 25 Questions</li>
                        <li>Mathematics: 25 Questions</li>
                        <li className="font-bold">Total: 75 Questions</li>
                        <li className="font-bold">Duration: 180 Minutes</li>
                    </ul>
                    <Button 
                        size="lg" 
                        className="w-full mt-6 bg-blue-600 hover:bg-blue-700" 
                        onClick={() => handleGenerateTest('jee')}
                        disabled={isLoading === 'jee'}
                    >
                         {isLoading === 'jee' ? <Loader2 className="mr-2 h-5 w-5 animate-spin" /> : <Bot className="mr-2 h-5 w-5" />}
                        {isLoading === 'jee' ? "Generating..." : "Start JEE Main Test"}
                    </Button>
                </CardContent>
            </Card>

             <Card 
              className="bg-secondary/30 border-green-500/30 p-6 rounded-2xl transition-all group relative overflow-hidden flex flex-col"
            >
                <CardHeader>
                    <CardTitle className="font-headline text-3xl">NEET Full Test</CardTitle>
                </CardHeader>
                <CardContent className="flex-1 flex flex-col justify-between">
                     <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                        <li>Physics: 50 Questions</li>
                        <li>Chemistry: 50 Questions</li>
                        <li className="text-sm italic">(Biology & Zoology coming soon)</li>
                        <li className="font-bold">Total: 100 Questions</li>
                        <li className="font-bold">Duration: 180 Minutes</li>
                    </ul>
                     <Button 
                        size="lg" 
                        className="w-full mt-6 bg-green-600 hover:bg-green-700"
                        onClick={() => handleGenerateTest('neet')}
                        disabled={isLoading === 'neet'}
                    >
                         {isLoading === 'neet' ? <Loader2 className="mr-2 h-5 w-5 animate-spin" /> : <Bot className="mr-2 h-5 w-5" />}
                        {isLoading === 'neet' ? "Generating..." : "Start NEET Test"}
                    </Button>
                </CardContent>
            </Card>
        </div>
        
        <div className="text-center pt-6">
            <h3 className="text-2xl font-headline font-semibold mb-4">Or, build your own practice set</h3>
             <Button asChild variant="outline" size="lg">
                <Link href="/mock-test/custom">
                    Create a Custom Test <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
            </Button>
        </div>
      </div>
    </div>
  );
}
